AppStore/Models/Scores.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppStore.Models
{
    public partial class Scores
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int AppId { get; set; }
        public int Score { get; set; }
    
        public virtual Apps Apps { get; set; }
        public virtual Users Users { get; set; }
    }
}

AppStore/Controllers/ScoresController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using AppStore.Models;

namespace AppStore.Controllers
{
    public class ScoresController : Controller
    {
        private AppStoreDbEntities db = new AppStoreDbEntities();

        // GET: Scores
        public async Task<ActionResult> Index()
        {
            var scores = db.Scores.Include(s => s.Apps).Include(s => s.Users);
            return View(await scores.ToListAsync());
        }


        // GET: Scores/Create
        public ActionResult Create()
        {
            ViewBag.AppId = new SelectList(db.Apps, "Id", "Title");
            ViewBag.UserId = new SelectList(db.Users, "Id", "Name");
            return View();
        }

        // POST: Scores/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,UserId,AppId,Score")] Scores scores)
        {
            if (ModelState.IsValid)
            {
                db.Scores.Add(scores);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.AppId = new SelectList(db.Apps, "Id", "Title", scores.AppId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "Name", scores.UserId);
            return View(scores);
        }



        public async Task<ActionResult> GenerateRandomScores()
        {
            Random r = new Random();

            List<int> userIds = (from user in db.Users select user.Id).ToList();
            List<int> appsIds = (from app in db.Apps select app.Id).ToList();

            for (int i = 0; i < 20; i++)
            {
                int userId = userIds[r.Next(0, userIds.Count)];
                int appId = appsIds[r.Next(0, appsIds.Count)];

                Users user = await  db.Users.FindAsync(userId);
                if (user != null)
                {
                    bool isExist = (from score in user.Scores where score.AppId == appId select true).FirstOrDefault();

                    if (!isExist)
                    {
                        user.Scores.Add(new Scores(){AppId =  appId, Users = user, Score = r.Next(1,6)});
                    }
                }
            }

            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }



        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public async Task<ActionResult> RemoveAllScores()
        {
            var scores = db.Scores.ToList();
            db.Scores.RemoveRange(scores);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

AppStore/Views/Scores/Create.cshtml
@model AppStore.Models.Scores

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Scores</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @if (User.Identity.IsAuthenticated)
                {
                    @Html.EditorFor(model => model.UserId, new { htmlAttributes = new { @class = "form-control", @hidden = "hidden" } })
                }
                else
                {
                    @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
                }                            @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AppId, "AppId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AppId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AppId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Score, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Score, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Score, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AppStore/Views/Scores/Index.cshtml
@model IEnumerable<AppStore.Models.Scores>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create", "Scores")
</p>
<p>
    @Html.ActionLink("Сгенерировать случайных оценок", "GenerateRandomScores", "Scores")
</p>
<p>
    @Html.ActionLink("Удалить все оценки", "RemoveAllScores", "Scores")
</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Score)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Apps.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Users.Name)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Score)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Apps.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Users.Name)
        </td>
    </tr>
}

</table>